package com.codexquota.app.testing

import com.codexquota.app.data.security.BridgeEndpoint
import java.security.KeyStore
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext
import okhttp3.WebSocket
import okhttp3.WebSocketListener
import okhttp3.mockwebserver.Dispatcher
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import okhttp3.mockwebserver.RecordedRequest

/**
 * A local Bridge that speaks the real v1 protocol over real TLS.
 *
 * It exists so the instrumentation tests can exercise the app's actual networking code — the pinning
 * trust manager, the credential interceptor, the JSON mapper, the WebSocket adapter — instead of a
 * fake standing in for them. The certificate chain it presents is generated by the same
 * [TestPki] the unit tests use, so the identity model under test is the same one.
 *
 * The server is deliberately literal about what it accepts: it answers only the routes v1 defines,
 * and it records every request so a test can assert what the app did and did not send.
 */
class FakeBridgeServer(
    /** The Bridge identity. The app pins the SHA-256 of this certificate's SPKI. */
    val identity: TestPki.Authority = TestPki.newAuthority("Codex Quota Bridge"),
    /**
     * The certificate the server presents.
     *
     * Overridable so a test can present a leaf that is expired, or issued for a different name, and
     * prove that the app refuses it rather than trusting whatever answered.
     */
    leafOverride: TestPki.Leaf? = null,
) {
    /** The host the certificate is issued for, and the host the app will dial. */
    val host: String = LOCALHOST

    private val leaf: TestPki.Leaf = leafOverride ?: TestPki.leafFor(identity, host)

    private val server = MockWebServer()

    /** Every request the server received, in order. */
    val received = mutableListOf<RecordedRequest>()

    /** The quota document served by `GET /api/v1/quota`. */
    var quotaJson: String = fixture("quota-v1.json")

    /** The history document served by `GET /api/v1/history`. */
    var historyJson: String = fixture("history-v1.json")

    /** The events document served by `GET /api/v1/events`. */
    var eventsJson: String = fixture("events-v1.json")

    /**
     * When set, the next quota request is answered with this status and v1 error code instead.
     *
     * @return a function that clears the override, so a test cannot leak it into a later assertion.
     */
    var quotaFailure: Pair<Int, String>? = null

    /** The pairing status the Bridge reports, as the wire name. */
    @Volatile
    var pairingStatus: String = "awaiting_local_approval"

    /** The token the Bridge issues exactly once, at the end of an approved pairing. */
    var issuedToken: String = SAMPLE_TOKEN

    /** The Bridge's own identifier. */
    var bridgeId: String = "bridge-1"

    private val pairingId = "pair-1"

    /** The live connection, once the app has upgraded. */
    @Volatile
    private var socket: WebSocket? = null

    /** The identity the app is expected to pin. */
    val identityFingerprint: String get() = identity.fingerprint

    /** The code a person would compare on the Windows pairing window. */
    val verificationCode: String get() = identity.verificationCode

    /** Starts the server and returns the endpoint the app should dial. */
    fun start(): BridgeEndpoint {
        server.useHttps(serverSslContext(), false)
        server.dispatcher = Router()
        server.start()

        return BridgeEndpoint(host, server.port)
    }

    /** Stops the server. Safe to call more than once. */
    fun stop() {
        runCatching { server.shutdown() }
    }

    /** Moves the pairing session to approved, as the person at the Windows machine would. */
    fun approvePairing() {
        pairingStatus = "approved"
    }

    /** Pushes one `quota.updated` frame to the connected app. */
    fun pushQuotaFrame(sequence: Long, shortRemainingPercent: Double, weeklyRemainingPercent: Double = 54.0) {
        val frame = wsFrame(sequence, shortRemainingPercent, weeklyRemainingPercent)

        socket?.send(frame)
    }

    /** Whether the app currently holds an upgraded connection. */
    val hasLiveConnection: Boolean get() = socket != null

    /** Every `Authorization` header the server ever received. */
    fun authorizationHeaders(): List<String> = received.mapNotNull { it.getHeader("Authorization") }

    /** Every request path the server ever received. */
    fun paths(): List<String> = received.mapNotNull { it.path }

    /**
     * The TLS context that presents the leaf **and the identity that signed it**.
     *
     * Presenting the chain is what makes the app's pin meaningful: it pins the last certificate, so a
     * server that presented only the leaf would be pinned to the leaf instead — which is the mistake
     * the identity model exists to prevent.
     */
    private fun serverSslContext(): javax.net.ssl.SSLSocketFactory {
        val password = "test-only".toCharArray()
        val keyStore = KeyStore.getInstance("PKCS12").apply { load(null) }

        keyStore.setKeyEntry(
            "leaf",
            leaf.keyPair.private,
            password,
            arrayOf(leaf.certificate, identity.certificate),
        )

        val keyManagers = KeyManagerFactory
            .getInstance(KeyManagerFactory.getDefaultAlgorithm())
            .apply { init(keyStore, password) }
            .keyManagers

        return SSLContext.getInstance("TLS")
            .apply { init(keyManagers, null, null) }
            .socketFactory
    }

    /** Routes the v1 surface. */
    private inner class Router : Dispatcher() {
        override fun dispatch(request: RecordedRequest): MockResponse {
            received += request

            val path = request.path.orEmpty()

            return when {
                path.startsWith("/api/v1/health") -> json(HEALTH)

                path.startsWith("/api/v1/ws") -> MockResponse().withWebSocketUpgrade(object : WebSocketListener() {
                    override fun onOpen(webSocket: WebSocket, response: okhttp3.Response) {
                        socket = webSocket
                        webSocket.send(helloFrame())
                    }

                    override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
                        socket = null
                    }

                    override fun onFailure(webSocket: WebSocket, t: Throwable, response: okhttp3.Response?) {
                        socket = null
                    }
                })

                path.startsWith("/api/v1/pairing/request") -> json(sessionJson())
                path.startsWith("/api/v1/pairing/claim") -> json(sessionJson())
                path.startsWith("/api/v1/pairing/status") -> json(sessionJson())

                path.startsWith("/api/v1/pairing/complete") -> json(credentialJson())

                path.startsWith("/api/v1/quota") -> quotaFailure?.let { (status, code) ->
                    json("""{"error":{"code":"$code","message":"the test asked for this","retryable":true}}""", status)
                } ?: json(quotaJson)

                path.startsWith("/api/v1/history") -> json(historyJson)
                path.startsWith("/api/v1/events") -> json(eventsJson)

                // Anything else is a route v1 does not define, and answering it would hide a bug in
                // the app's own request building.
                else -> MockResponse().setResponseCode(404)
            }
        }
    }

    private fun json(body: String, status: Int = 200): MockResponse =
        MockResponse()
            .setResponseCode(status)
            .setHeader("Content-Type", "application/json; charset=utf-8")
            .setBody(body)

    private fun sessionJson(): String =
        """{"pairingId":"$pairingId","status":"$pairingStatus","verificationCode":"$verificationCode",""" +
            """"displayName":"Android phone","expiresAt":"2026-09-22T13:35:00Z"}"""

    private fun credentialJson(): String =
        """{"schemaVersion":1,"deviceId":"device-1","token":"$issuedToken"}"""

    private fun helloFrame(): String =
        """{"type":"hello","apiVersion":"v1","bridgeVersion":"1.0.0"}"""

    private fun wsFrame(sequence: Long, shortRemaining: Double, weeklyRemaining: Double): String =
        """{"type":"quota.updated","sequence":$sequence,"payload":{""" +
            """"schemaVersion":1,"generatedAt":"2026-09-22T13:30:00Z","source":"codex_app_server",""" +
            """"status":"online","lastSuccessfulSyncAt":"2026-09-22T13:30:00Z","windows":{""" +
            """"shortWindow":{"usedPercent":${100.0 - shortRemaining},"remainingPercent":$shortRemaining,""" +
            """"windowMinutes":300,"resetsAt":"2026-09-22T15:42:00Z"},""" +
            """"weekly":{"usedPercent":${100.0 - weeklyRemaining},"remainingPercent":$weeklyRemaining,""" +
            """"windowMinutes":10080,"resetsAt":"2026-09-28T00:00:00Z"}}}}"""

    companion object {
        /**
         * The address the server binds and the app dials.
         *
         * The IPv4 loopback literal, not `localhost`: `localhost` resolves to `::1` on some JVMs
         * while the server binds `127.0.0.1`, which produced a connection failure unrelated to
         * anything the tests are about.
         */
        const val LOCALHOST = "127.0.0.1"

        /** A stand-in credential. It is never real, and it exists so a test can search for it. */
        const val SAMPLE_TOKEN = "sample-device-token-not-a-secret"

        private const val HEALTH = """{"status":"ok","apiVersion":"v1"}"""

        /**
         * Reads a shared v1 contract fixture.
         *
         * The same files the Windows tests and the JVM unit tests are proven against, so the fake
         * Bridge cannot serve a document the real Bridge would not.
         */
        private fun fixture(name: String): String =
            requireNotNull(FakeBridgeServer::class.java.classLoader?.getResourceAsStream(name)) {
                "$name is missing from the instrumentation resources; the contracts/v1 directory " +
                    "must be on the androidTest resource path."
            }.use { it.readBytes().toString(Charsets.UTF_8) }
    }
}
